spring:
  application:
    name: customer-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/feign_client
    username: postgres
    password: 1111@2222@
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081